name: corsac_jwt
version: 0.4.1-dev
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  asn1lib: "^0.9.0-nullsafety.0"
  crypto: "^3.0.0"
  logging: "^1.0.0"
  pointycastle: "^3.0.0-nullsafety.2"
  rsa_pkcs:
    git:
      url: https://github.com/luiz-simples/rsa_pkcs.git
      branch: master
